export const USER_SOCKET_CONNECTED_CHANNEL = "USER_SOCKET_CONNECTED_CHANNEL";
export const SELLER_SOCKET_CONNECTED_CHANNEL =
  "SELLER_SOCKET_CONNECTED_CHANNEL";
export const USER_SOCKET_EVENT = {
  CONNECTED: "connected",
  DISCONNECTED: "disconnected",
};
