export const GHN_BASE_URL = "https://online-gateway.ghn.vn";

export const GHN_REQUIRED_NOTE = {
  CHOTHUHANG: "CHOTHUHANG",
  CHOXEMHANGKHONGTHU: "CHOXEMHANGKHONGTHU",
  KHONGCHOXEMHANG: "KHONGCHOXEMHANG",
} as const;

